services:
  codegardenapi:
    image: codegardenapi
    build:
      context: .
      dockerfile: CodeGardenApi/Dockerfile
    ports:
        - "8080:8080"
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Secret123!"
      ACCEPT_EULA: "Y"
    volumes:
      - db_data:/var/opt/mssql
volumes:
  db_data: